version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    #warning mysql cmd
    #ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
    platform: linux/amd64
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./local/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_DATABASE=devops
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - devops
  devops:
    depends_on:
      - mysql
    privileged: true
    image: cubegroup/devops
#    image: cubegroup/devops-devops-shell-java
#    image: cubegroup/devops-devops-shell-devops-shell-java-node
    platform: linux/amd64
    container_name: devops
    restart: always
    ports:
      - 8080:80
    environment:
      - WEB_DEBUG=1
      - DB_DEBUG=1
      - DB_HOST=mysql
      - DB_USERNAME=devops
      - DB_PASSWORD=devops
      - DB_NAME=devops
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
    links:
      - mysql
    networks:
      - devops
networks:
  devops:
    driver: bridge