version: "3.0"

services:
  ngnix:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/logs:/var/log/nginx
      - /data/nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime